const ADD_MAIN_FIELDS = "ADD_MAIN_FIELDS";
const ADD_CUSTOM_FIELDS = "ADD_CUSTOM_FIELDS";
const ADD_ITEM_TAGS = "ADD_ITEM_TAGS";
const ADD_COMMENTS = "ADD_COMMENTS";
const ADD_COMMENT = "ADD_COMMENT";


export {ADD_MAIN_FIELDS,ADD_ITEM_TAGS,ADD_CUSTOM_FIELDS,ADD_COMMENTS, ADD_COMMENT}