const ADD_COLLECTION = "ADD_COLLECTION";
const ADD_CARD = "ADD_CARD";
const DELETE_CARDS = "DELETE_CARDS";
const ADD_FIELDS = "ADD_FIELDS";

export {ADD_COLLECTION, ADD_CARD, ADD_FIELDS, DELETE_CARDS}